services:
  rating-db:
    image: postgres:latest
    container_name: Rating-Service-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - rating-network

  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: rating-zookeeper
    restart: unless-stopped
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
    networks:
      - rating-network

  kafka:
    image: wurstmeister/kafka:latest
    container_name: rating-kafka
    restart: unless-stopped
    environment:
      KAFKA_LOG_DIRS: /kafka-data
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: EXTERNAL://:9092,INTERNAL://:9094
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://localhost:8001,INTERNAL://kafka:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_CREATE_TOPICS: "rating.added:1:1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    depends_on:
      - zookeeper
    networks:
      - rating-network
    ports:
      - "8001:9092"
    volumes:
      - rating-kafka-data:/kafka/data

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: rating-kafka-ui
    restart: unless-stopped
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: rating-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9094
      DYNAMIC_CONFIG_ENABLED: "true"
    ports:
      - "8080:8080"
    networks:
      - rating-network

networks:
  rating-network:
    driver: bridge

volumes:
  rating-postgres-data:
  rating-kafka-data: